import type { MissionTemplate } from '../domain/types'

export const missionTemplates: MissionTemplate[] = [
  {
    id: 'mt_courier',
    category: 'courier',
    title: 'Courier Run',
    summaryTemplate: 'Carry a sealed package to {destination} before it loses its value.',
    minRank: 'initiate',
    stages: [
      { id: 'travel_speed', label: 'Making good time', attributes: ['mobility'], weight: 0.6, difficultyBase: 18 },
      { id: 'discretion', label: 'Avoiding trouble on the road', attributes: ['control'], weight: 0.4, difficultyBase: 15 },
    ],
    durationRange: [1, 2],
    travelRange: [0, 1],
    rewardRange: [30, 60],
    reputationRewardRange: [1, 2],
    dangerBand: 'low',
    baseInfoConfidence: 'good',
    recommendedTeamSize: [1, 2],
  },
  {
    id: 'mt_escort',
    category: 'escort',
    title: 'Civilian Escort',
    summaryTemplate: 'Escort a civilian party safely to {destination}.',
    minRank: 'initiate',
    stages: [
      { id: 'travel_safety', label: 'Keeping the party safe on the road', attributes: ['combat', 'mobility'], weight: 0.5, difficultyBase: 22 },
      { id: 'client_confidence', label: 'Keeping the client calm and cooperative', attributes: ['presence'], weight: 0.5, difficultyBase: 18 },
    ],
    durationRange: [1, 3],
    travelRange: [0, 1],
    rewardRange: [40, 80],
    reputationRewardRange: [1, 3],
    dangerBand: 'low',
    baseInfoConfidence: 'good',
    recommendedTeamSize: [2, 3],
  },
  {
    id: 'mt_caravan_protection',
    category: 'caravan_protection',
    title: 'Caravan Protection',
    summaryTemplate: 'Guard a merchant caravan travelling through contested country near {destination}.',
    minRank: 'initiate',
    stages: [
      { id: 'ambush_defence', label: 'Repelling an ambush', attributes: ['combat'], weight: 0.5, difficultyBase: 32 },
      { id: 'route_planning', label: 'Choosing a safe route', attributes: ['intelligence'], weight: 0.25, difficultyBase: 25 },
      { id: 'endurance', label: 'Enduring the long haul', attributes: ['resilience'], weight: 0.25, difficultyBase: 25 },
    ],
    durationRange: [2, 4],
    travelRange: [1, 2],
    rewardRange: [70, 130],
    reputationRewardRange: [2, 4],
    dangerBand: 'moderate',
    baseInfoConfidence: 'fair',
    recommendedTeamSize: [2, 4],
  },
  {
    id: 'mt_missing_person',
    category: 'missing_person',
    title: 'Missing Person Search',
    summaryTemplate: 'Locate a person who vanished near {destination} before the trail goes cold.',
    minRank: 'initiate',
    stages: [
      { id: 'tracking', label: 'Following the trail', attributes: ['mobility', 'intelligence'], weight: 0.5, difficultyBase: 28 },
      { id: 'questioning', label: 'Questioning locals', attributes: ['presence', 'intelligence'], weight: 0.3, difficultyBase: 22 },
      { id: 'recovery', label: 'Handling what is found', attributes: ['resilience'], weight: 0.2, difficultyBase: 20 },
    ],
    durationRange: [2, 3],
    travelRange: [0, 1],
    rewardRange: [50, 100],
    reputationRewardRange: [1, 3],
    dangerBand: 'low',
    baseInfoConfidence: 'fair',
    recommendedTeamSize: [1, 3],
  },
  {
    id: 'mt_bandit_suppression',
    category: 'bandit_suppression',
    title: 'Bandit Suppression',
    summaryTemplate: 'Break up a bandit camp threatening the roads near {destination}.',
    minRank: 'field_operative',
    stages: [
      { id: 'assault', label: 'Storming the camp', attributes: ['combat'], weight: 0.55, difficultyBase: 40 },
      { id: 'coordination', label: 'Coordinating the attack', attributes: ['presence', 'control'], weight: 0.25, difficultyBase: 32 },
      { id: 'mop_up', label: 'Mopping up stragglers', attributes: ['mobility'], weight: 0.2, difficultyBase: 28 },
    ],
    durationRange: [2, 4],
    travelRange: [1, 2],
    rewardRange: [90, 160],
    reputationRewardRange: [3, 5],
    dangerBand: 'moderate',
    baseInfoConfidence: 'fair',
    recommendedTeamSize: [2, 4],
  },
  {
    id: 'mt_wildlife_threat',
    category: 'wildlife_threat',
    title: 'Wildlife Threat',
    summaryTemplate: 'Deal with a dangerous beast harassing farms around {destination}.',
    minRank: 'initiate',
    stages: [
      { id: 'tracking_beast', label: 'Tracking the beast', attributes: ['mobility', 'intelligence'], weight: 0.4, difficultyBase: 26 },
      { id: 'takedown', label: 'Bringing it down safely', attributes: ['combat'], weight: 0.6, difficultyBase: 30 },
    ],
    durationRange: [1, 3],
    travelRange: [0, 1],
    rewardRange: [45, 90],
    reputationRewardRange: [1, 3],
    dangerBand: 'moderate',
    baseInfoConfidence: 'fair',
    recommendedTeamSize: [1, 3],
  },
  {
    id: 'mt_sabotage_investigation',
    category: 'sabotage_investigation',
    title: 'Sabotage Investigation',
    summaryTemplate: 'Find out who has been sabotaging operations at {destination}.',
    minRank: 'field_operative',
    stages: [
      { id: 'evidence', label: 'Gathering evidence quietly', attributes: ['intelligence', 'control'], weight: 0.5, difficultyBase: 34 },
      { id: 'confrontation', label: 'Confronting the culprit', attributes: ['presence', 'combat'], weight: 0.5, difficultyBase: 32 },
    ],
    durationRange: [2, 3],
    travelRange: [0, 1],
    rewardRange: [70, 120],
    reputationRewardRange: [2, 4],
    dangerBand: 'moderate',
    baseInfoConfidence: 'poor',
    sensitivity: true,
    recommendedTeamSize: [2, 3],
  },
  {
    id: 'mt_village_defence',
    category: 'village_defence',
    title: 'Village Defence',
    summaryTemplate: 'Reinforce the defences of {destination} against an expected raid.',
    minRank: 'field_operative',
    stages: [
      { id: 'fortify', label: 'Preparing defences in time', attributes: ['intelligence', 'control'], weight: 0.3, difficultyBase: 30 },
      { id: 'hold_the_line', label: 'Holding the line', attributes: ['combat', 'resilience'], weight: 0.7, difficultyBase: 42 },
    ],
    durationRange: [2, 4],
    travelRange: [1, 2],
    rewardRange: [90, 150],
    reputationRewardRange: [3, 6],
    dangerBand: 'high',
    baseInfoConfidence: 'fair',
    recommendedTeamSize: [3, 4],
  },
  {
    id: 'mt_intelligence_gathering',
    category: 'intelligence_gathering',
    title: 'Intelligence Gathering',
    summaryTemplate: 'Quietly gather information on activity around {destination}.',
    minRank: 'initiate',
    stages: [
      { id: 'observation', label: 'Watching without being seen', attributes: ['mobility', 'control'], weight: 0.5, difficultyBase: 28 },
      { id: 'analysis', label: 'Making sense of what was seen', attributes: ['intelligence'], weight: 0.5, difficultyBase: 26 },
    ],
    durationRange: [2, 3],
    travelRange: [0, 2],
    rewardRange: [50, 90],
    reputationRewardRange: [1, 3],
    dangerBand: 'low',
    baseInfoConfidence: 'fair',
    recommendedTeamSize: [1, 2],
  },
  {
    id: 'mt_fugitive_pursuit',
    category: 'fugitive_pursuit',
    title: 'Fugitive Pursuit',
    summaryTemplate: 'Track down a fugitive fleeing toward {destination}.',
    minRank: 'field_operative',
    stages: [
      { id: 'pursuit', label: 'Catching up before the trail is lost', attributes: ['mobility'], weight: 0.45, difficultyBase: 38 },
      { id: 'capture', label: 'Taking the fugitive down without a mess', attributes: ['combat', 'control'], weight: 0.55, difficultyBase: 40 },
    ],
    durationRange: [2, 4],
    travelRange: [1, 2],
    rewardRange: [80, 140],
    reputationRewardRange: [2, 4],
    dangerBand: 'moderate',
    baseInfoConfidence: 'poor',
    recommendedTeamSize: [2, 3],
  },
  {
    id: 'mt_hostage_rescue',
    category: 'hostage_rescue',
    title: 'Hostage Rescue',
    summaryTemplate: 'Recover a hostage held somewhere near {destination} before it is too late.',
    minRank: 'veteran',
    stages: [
      { id: 'infiltrate_site', label: 'Getting to the hostage unseen', attributes: ['mobility', 'control'], weight: 0.4, difficultyBase: 48 },
      { id: 'extraction_fight', label: 'Fighting through if discovered', attributes: ['combat'], weight: 0.4, difficultyBase: 50 },
      { id: 'hostage_care', label: 'Keeping the hostage safe and calm', attributes: ['presence', 'resilience'], weight: 0.2, difficultyBase: 35 },
    ],
    durationRange: [2, 4],
    travelRange: [1, 2],
    rewardRange: [120, 220],
    reputationRewardRange: [4, 7],
    dangerBand: 'high',
    baseInfoConfidence: 'poor',
    recommendedTeamSize: [2, 4],
  },
  {
    id: 'mt_infiltration',
    category: 'infiltration',
    title: 'Infiltration',
    summaryTemplate: 'Slip into a guarded site near {destination} to plant or retrieve something of value.',
    minRank: 'field_operative',
    stages: [
      { id: 'bypass_guards', label: 'Bypassing the guards', attributes: ['mobility', 'control'], weight: 0.5, difficultyBase: 44 },
      { id: 'objective', label: 'Completing the objective undetected', attributes: ['technique', 'intelligence'], weight: 0.5, difficultyBase: 42 },
    ],
    durationRange: [2, 3],
    travelRange: [1, 2],
    rewardRange: [100, 170],
    reputationRewardRange: [2, 5],
    dangerBand: 'high',
    baseInfoConfidence: 'poor',
    sensitivity: true,
    recommendedTeamSize: [2, 3],
  },
  {
    id: 'mt_diplomatic_escort',
    category: 'diplomatic_escort',
    title: 'Diplomatic Escort',
    summaryTemplate: 'Escort a diplomat to sensitive talks at {destination} without incident.',
    minRank: 'field_operative',
    stages: [
      { id: 'protect_envoy', label: 'Protecting the envoy', attributes: ['combat', 'presence'], weight: 0.5, difficultyBase: 36 },
      { id: 'decorum', label: 'Maintaining decorum and discretion', attributes: ['presence', 'control'], weight: 0.5, difficultyBase: 34 },
    ],
    durationRange: [2, 3],
    travelRange: [1, 2],
    rewardRange: [90, 150],
    reputationRewardRange: [3, 6],
    dangerBand: 'moderate',
    baseInfoConfidence: 'good',
    sensitivity: true,
    recommendedTeamSize: [2, 3],
  },
  {
    id: 'mt_smuggling_interception',
    category: 'smuggling_interception',
    title: 'Smuggling Interception',
    summaryTemplate: 'Intercept a smuggling operation moving contraband through {destination}.',
    minRank: 'field_operative',
    stages: [
      { id: 'stakeout', label: 'Timing the interception', attributes: ['intelligence', 'control'], weight: 0.4, difficultyBase: 38 },
      { id: 'confrontation_smuggle', label: 'Confronting the smugglers', attributes: ['combat'], weight: 0.6, difficultyBase: 42 },
    ],
    durationRange: [2, 3],
    travelRange: [1, 2],
    rewardRange: [90, 160],
    reputationRewardRange: [2, 4],
    dangerBand: 'moderate',
    baseInfoConfidence: 'fair',
    recommendedTeamSize: [2, 3],
  },
  {
    id: 'mt_ruin_exploration',
    category: 'ruin_exploration',
    title: 'Ruin Exploration',
    summaryTemplate: 'Explore old ruins near {destination} rumoured to hold something valuable.',
    minRank: 'field_operative',
    stages: [
      { id: 'navigate_ruins', label: 'Navigating unstable ruins', attributes: ['mobility', 'intelligence'], weight: 0.5, difficultyBase: 40 },
      { id: 'hidden_dangers', label: 'Surviving hidden dangers', attributes: ['resilience', 'control'], weight: 0.5, difficultyBase: 44 },
    ],
    durationRange: [2, 4],
    travelRange: [1, 3],
    rewardRange: [100, 180],
    reputationRewardRange: [2, 4],
    dangerBand: 'high',
    baseInfoConfidence: 'poor',
    recommendedTeamSize: [2, 4],
  },
  {
    id: 'mt_disaster_relief',
    category: 'disaster_relief',
    title: 'Disaster Relief',
    summaryTemplate: 'Help {destination} recover after a flood, fire, or collapse.',
    minRank: 'initiate',
    stages: [
      { id: 'rescue_efforts', label: 'Pulling people to safety', attributes: ['resilience', 'combat'], weight: 0.5, difficultyBase: 30 },
      { id: 'organise_relief', label: 'Organising relief efforts', attributes: ['presence', 'intelligence'], weight: 0.5, difficultyBase: 26 },
    ],
    durationRange: [2, 4],
    travelRange: [0, 2],
    rewardRange: [60, 110],
    reputationRewardRange: [3, 6],
    dangerBand: 'moderate',
    baseInfoConfidence: 'good',
    recommendedTeamSize: [2, 4],
  },
  {
    id: 'mt_counter_espionage',
    category: 'counter_espionage',
    title: 'Counter-Espionage',
    summaryTemplate: 'Root out a spy operating within or near {destination}.',
    minRank: 'veteran',
    stages: [
      { id: 'suspect_id', label: 'Identifying the real suspect', attributes: ['intelligence'], weight: 0.5, difficultyBase: 46 },
      { id: 'quiet_resolution', label: 'Resolving it without a scandal', attributes: ['control', 'presence'], weight: 0.5, difficultyBase: 44 },
    ],
    durationRange: [2, 3],
    travelRange: [0, 1],
    rewardRange: [110, 190],
    reputationRewardRange: [3, 6],
    dangerBand: 'high',
    baseInfoConfidence: 'poor',
    sensitivity: true,
    recommendedTeamSize: [1, 3],
  },
  {
    id: 'mt_border_patrol',
    category: 'border_patrol',
    title: 'Border Patrol',
    summaryTemplate: 'Patrol the contested border near {destination} for a stretch of days.',
    minRank: 'initiate',
    stages: [
      { id: 'patrol_endurance', label: 'Enduring the long patrol', attributes: ['resilience', 'mobility'], weight: 0.5, difficultyBase: 26 },
      { id: 'incident_response', label: 'Responding to incidents along the line', attributes: ['combat', 'intelligence'], weight: 0.5, difficultyBase: 30 },
    ],
    durationRange: [3, 5],
    travelRange: [1, 2],
    rewardRange: [70, 120],
    reputationRewardRange: [2, 4],
    dangerBand: 'moderate',
    baseInfoConfidence: 'fair',
    recommendedTeamSize: [2, 4],
  },
  {
    id: 'mt_assassination_prevention',
    category: 'assassination_prevention',
    title: 'Assassination Prevention',
    summaryTemplate: 'Protect a target in {destination} believed to be marked for assassination.',
    minRank: 'veteran',
    stages: [
      { id: 'threat_assessment', label: 'Identifying the real threat in time', attributes: ['intelligence'], weight: 0.35, difficultyBase: 50 },
      { id: 'close_protection', label: 'Close protection under pressure', attributes: ['combat', 'control'], weight: 0.65, difficultyBase: 54 },
    ],
    durationRange: [2, 4],
    travelRange: [1, 2],
    rewardRange: [150, 260],
    reputationRewardRange: [4, 8],
    dangerBand: 'high',
    baseInfoConfidence: 'poor',
    sensitivity: true,
    recommendedTeamSize: [2, 4],
  },
  {
    id: 'mt_high_risk_capture',
    category: 'high_risk_capture',
    title: 'High-Risk Capture',
    summaryTemplate: 'Capture a dangerous, well-guarded target near {destination} alive.',
    minRank: 'elite',
    stages: [
      { id: 'breach', label: 'Breaching the target’s defences', attributes: ['combat', 'technique'], weight: 0.4, difficultyBase: 58 },
      { id: 'subdue', label: 'Subduing the target without killing them', attributes: ['control', 'combat'], weight: 0.35, difficultyBase: 60 },
      { id: 'extraction', label: 'Getting out before reinforcements arrive', attributes: ['mobility'], weight: 0.25, difficultyBase: 52 },
    ],
    durationRange: [2, 4],
    travelRange: [1, 3],
    rewardRange: [200, 340],
    reputationRewardRange: [5, 9],
    dangerBand: 'unknown',
    baseInfoConfidence: 'poor',
    sensitivity: true,
    recommendedTeamSize: [3, 4],
  },
]

export function missionTemplateById(id: string): MissionTemplate {
  const template = missionTemplates.find((t) => t.id === id)
  if (!template) throw new Error(`Unknown mission template id: ${id}`)
  return template
}
