import type { Attributes, RankId, RecruitCandidate, Warrior } from '../domain/types'

function attrs(partial: Partial<Attributes>): Attributes {
  const base: Attributes = {
    combat: 20,
    technique: 20,
    control: 20,
    intelligence: 20,
    mobility: 20,
    presence: 20,
    resilience: 20,
  }
  return { ...base, ...partial }
}

const wageByRank: Record<RankId, number> = {
  initiate: 2,
  field_operative: 4,
  veteran: 7,
  elite: 12,
}

function baseWarrior(input: {
  name: string
  age: number
  rank: RankId
  archetype: string
  attributes: Attributes
  traitIds: string[]
  techniqueIds?: string[]
  specialityIds?: string[]
  background?: string
}): Omit<Warrior, 'id'> {
  return {
    name: input.name,
    age: input.age,
    rank: input.rank,
    archetype: input.archetype,
    attributes: input.attributes,
    traitIds: input.traitIds,
    techniqueIds: input.techniqueIds ?? [],
    specialityIds: input.specialityIds ?? [],
    loyalty: 60,
    morale: 65,
    fatigue: 0,
    health: 100,
    experience: 0,
    level: 1,
    injuries: [],
    status: 'available',
    teamId: null,
    missionHistory: [],
    relationships: {},
    wage: wageByRank[input.rank],
    background: input.background,
    joinedDay: 1,
  }
}

export const startingWarriors: Omit<Warrior, 'id'>[] = [
  baseWarrior({
    name: 'Kessa Ashgrove',
    age: 34,
    rank: 'veteran',
    archetype: 'Vanguard Fighter',
    attributes: attrs({ combat: 62, resilience: 58, presence: 55, mobility: 40, control: 45, intelligence: 35, technique: 40 }),
    traitIds: ['trait_natural_leader', 'trait_loyal'],
    techniqueIds: ['tech_iron_guard', 'tech_rally_cry'],
    background: 'One of the first to answer the call when the Enclave was founded. Steady and well-liked.',
  }),
  baseWarrior({
    name: 'Joran Blackwell',
    age: 26,
    rank: 'field_operative',
    archetype: 'Blade Specialist',
    attributes: attrs({ combat: 58, mobility: 42, resilience: 38, technique: 35, control: 28, intelligence: 25, presence: 30 }),
    traitIds: ['trait_reckless'],
    techniqueIds: ['tech_piercing_strike'],
    background: 'A former duelist who traded prize fighting for steadier, if more dangerous, work.',
  }),
  baseWarrior({
    name: 'Dessa Cindermoor',
    age: 29,
    rank: 'field_operative',
    archetype: 'Field Medic',
    attributes: attrs({ intelligence: 50, resilience: 45, control: 40, presence: 35, combat: 25, mobility: 30, technique: 30 }),
    traitIds: ['trait_medic', 'trait_calm_under_pressure'],
    techniqueIds: ['tech_field_suture'],
    background: 'Trained under a travelling physician before the Enclave gave her a permanent home.',
  }),
  baseWarrior({
    name: 'Aren Dravenwood',
    age: 19,
    rank: 'initiate',
    archetype: 'Scout',
    attributes: attrs({ mobility: 48, control: 32, intelligence: 30, combat: 25, presence: 20, resilience: 28, technique: 22 }),
    traitIds: ['trait_scout', 'trait_fast_learner'],
    background: 'Grew up running trade routes on foot. Nothing in the hills escapes his notice.',
  }),
  baseWarrior({
    name: 'Fenna Emberfall',
    age: 22,
    rank: 'initiate',
    archetype: 'Tactician',
    attributes: attrs({ intelligence: 44, control: 38, presence: 28, combat: 22, mobility: 26, resilience: 24, technique: 26 }),
    traitIds: ['trait_cautious'],
    background: 'Studied siege tactics from old borrowed texts before ever holding a real assignment.',
  }),
  baseWarrior({
    name: 'Garrick Fenmarsh',
    age: 38,
    rank: 'veteran',
    archetype: 'Vanguard Fighter',
    attributes: attrs({ combat: 60, resilience: 54, presence: 42, control: 38, mobility: 32, intelligence: 30, technique: 34 }),
    traitIds: ['trait_natural_leader'],
    techniqueIds: ['tech_iron_guard'],
    background: 'A quiet veteran of border skirmishes who prefers earning trust to giving orders.',
  }),
  baseWarrior({
    name: 'Halda Grayvale',
    age: 27,
    rank: 'field_operative',
    archetype: 'Marksman',
    attributes: attrs({ control: 48, combat: 42, intelligence: 34, mobility: 30, resilience: 30, presence: 24, technique: 32 }),
    traitIds: ['trait_calm_under_pressure'],
    techniqueIds: ['tech_focused_mind'],
    background: 'Precise and unhurried, even when everything around her is not.',
  }),
  baseWarrior({
    name: 'Isolde Hollowmere',
    age: 21,
    rank: 'initiate',
    archetype: 'Infiltrator',
    attributes: attrs({ mobility: 40, control: 36, technique: 30, intelligence: 28, combat: 24, presence: 22, resilience: 24 }),
    traitIds: ['trait_tracker'],
    background: 'Slips through crowds and quiet places alike without drawing a second glance.',
  }),
  baseWarrior({
    name: 'Orin Ironcliff',
    age: 41,
    rank: 'elite',
    archetype: 'Vanguard Fighter',
    attributes: attrs({ combat: 78, presence: 60, resilience: 62, control: 45, mobility: 38, intelligence: 40, technique: 50 }),
    traitIds: ['trait_natural_leader', 'trait_ambitious'],
    techniqueIds: ['tech_iron_guard', 'tech_piercing_strike', 'tech_rally_cry'],
    background: 'The single most accomplished operative to join the Enclave so far. Everyone knows his name.',
  }),
  baseWarrior({
    name: 'Perrin Justwind',
    age: 20,
    rank: 'initiate',
    archetype: 'Support Operative',
    attributes: attrs({ presence: 30, resilience: 30, combat: 28, intelligence: 28, mobility: 26, control: 26, technique: 24 }),
    traitIds: ['trait_loyal', 'trait_poor_team_player'],
    background: 'Devoted to the Enclave, but still learning how to work well with others.',
  }),
  baseWarrior({
    name: 'Quenna Kestrel',
    age: 24,
    rank: 'field_operative',
    archetype: 'Scout',
    attributes: attrs({ mobility: 52, combat: 34, control: 26, intelligence: 30, resilience: 28, presence: 24, technique: 28 }),
    traitIds: ['trait_scout', 'trait_reckless'],
    techniqueIds: ['tech_shadowstep'],
    background: 'Fast, fearless, and a little too fond of cutting things close.',
  }),
  baseWarrior({
    name: 'Roswyn Longshade',
    age: 18,
    rank: 'initiate',
    archetype: 'Field Medic',
    attributes: attrs({ intelligence: 36, resilience: 34, control: 30, combat: 20, mobility: 24, presence: 24, technique: 22 }),
    traitIds: ['trait_medic', 'trait_gifted'],
    background: 'The youngest of the founding roster, and already showing real aptitude for field medicine.',
  }),
]

export const startingRecruitPool: Omit<RecruitCandidate, 'id' | 'expiresDay'>[] = [
  {
    name: 'Maren Moorwatch',
    age: 19,
    rank: 'initiate',
    attributes: attrs({ combat: 50, mobility: 38, resilience: 30, control: 20, intelligence: 22, presence: 24, technique: 26 }),
    traitIds: ['trait_reckless', 'trait_gifted'],
    specialityIds: [],
    wage: 3,
    signingCost: 40,
    background: 'A talented young brawler with no patience for caution.',
    archetype: 'Blade Specialist',
  },
  {
    name: 'Nessa Nightbourne',
    age: 30,
    rank: 'field_operative',
    attributes: attrs({ combat: 36, control: 34, resilience: 36, mobility: 32, intelligence: 30, presence: 30, technique: 30 }),
    traitIds: ['trait_loyal'],
    specialityIds: [],
    wage: 4,
    signingCost: 60,
    background: 'Reliable and unremarkable in the best possible way. Never the star, never the weak link.',
    archetype: 'Support Operative',
  },
  {
    name: 'Sael Oakhurst',
    age: 23,
    rank: 'initiate',
    attributes: attrs({ intelligence: 42, resilience: 38, control: 32, combat: 16, mobility: 22, presence: 26, technique: 24 }),
    traitIds: ['trait_medic'],
    specialityIds: [],
    wage: 3,
    signingCost: 45,
    background: 'A gifted healer with almost no combat training to speak of.',
    archetype: 'Field Medic',
  },
  {
    name: 'Tamsin Palewood',
    age: 44,
    rank: 'veteran',
    attributes: attrs({ combat: 56, resilience: 52, presence: 48, control: 42, intelligence: 38, mobility: 30, technique: 40 }),
    traitIds: ['trait_calm_under_pressure', 'trait_natural_leader'],
    specialityIds: [],
    wage: 8,
    signingCost: 180,
    background: 'A veteran of another Enclave, looking for a fresh start. Expensive, but proven.',
    archetype: 'Vanguard Fighter',
  },
  {
    name: 'Ulric Quillstone',
    age: 21,
    rank: 'initiate',
    attributes: attrs({ technique: 48, control: 40, intelligence: 36, combat: 26, mobility: 28, presence: 22, resilience: 24 }),
    traitIds: ['trait_gifted', 'trait_ambitious'],
    specialityIds: [],
    wage: 3,
    signingCost: 50,
    background: 'Unusually talented, though something about his past does not quite add up.',
    hiddenLoyaltyNote: 'Rumoured to have left his last posting under a cloud. Loyalty may be shakier than it appears.',
    archetype: 'Infiltrator',
  },
  {
    name: 'Vessa Redbrook',
    age: 27,
    rank: 'field_operative',
    attributes: attrs({ intelligence: 46, control: 38, presence: 34, combat: 26, mobility: 28, resilience: 28, technique: 30 }),
    traitIds: ['trait_cautious'],
    specialityIds: [],
    wage: 4,
    signingCost: 70,
    background: 'A methodical planner who would rather scout a route three times than fight her way out once.',
    archetype: 'Tactician',
  },
  {
    name: 'Wren Stormwick',
    age: 20,
    rank: 'initiate',
    attributes: attrs({ mobility: 44, control: 30, intelligence: 28, combat: 24, presence: 20, resilience: 26, technique: 24 }),
    traitIds: ['trait_scout', 'trait_fast_learner'],
    specialityIds: [],
    wage: 3,
    signingCost: 45,
    background: 'Quick on their feet and quicker to learn. Still rough around the edges.',
    archetype: 'Scout',
  },
  {
    name: 'Yorik Thistledown',
    age: 25,
    rank: 'field_operative',
    attributes: attrs({ combat: 48, presence: 38, mobility: 34, control: 30, intelligence: 26, resilience: 32, technique: 32 }),
    traitIds: ['trait_ambitious'],
    specialityIds: [],
    wage: 4,
    signingCost: 75,
    background: 'Skilled and hungry for recognition. Wants to lead a team sooner rather than later.',
    archetype: 'Blade Specialist',
  },
]
